version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=spotify
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/
volumes:
  db:
    driver: local